
name: 'Build & publish all NPM packages'

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  build-and-publish:
    name: 'Build and publish'
    runs-on: ubuntu-latest
    environment: prod
    # env:
    #   FOO: 'bar'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci

          cd packages
          make build
          make publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
