
name: 'Publish @testuj.to/react StoryBook'

on:
  push:
    branches: [ 'master' ]

permissions:
  contents: read

jobs:
  build-and-publish-react-storybook:
    name: 'Publish @testuj.to/react StoryBook'
    runs-on: ubuntu-latest
    environment: prod
    # env:
    #   FOO: 'bar'
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: chromaui/action@v1
        with:
          workingDir: packages/@testuj.to/react
          buildScriptName: docs:build
          projectToken: ${{ secrets.CHROMATIC_REACT_TOKEN }}
          # token: ${{ secrets.GITHUB_TOKEN }}
